version: '3.3'
services:

  mongodb:
    restart: unless-stopped
    image: mongo:5.0
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"
    command: mongod --setParameter diagnosticDataCollectionEnabled=false # --quiet


  ota:
    image: flashspys/nginx-static
    restart: unless-stopped
    container_name: ota
    ports:
      - "5004:5004"
    volumes:
      - ./ota/data:/static
      - ./ota/config/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=ota.iotcloud.cesarsanz.dev
      - VIRTUAL_PORT=5004
      - LETSENCRYPT_HOST=ota.iotcloud.cesarsanz.dev

  modules2:
    container_name: modules2
    build: ./python-modules2
    env_file:
      - 'variables.env'
    restart: unless-stopped
    volumes:
      - ./python-modules2/logs:/app/logs
    secrets:
      - modules_secrets
    cap_add:
      - SYS_PTRACE

secrets:
  modules_secrets:
      file: ./python-modules/secrets